# Permalinks
permalink:           pretty

# Setup
title:               Tailor
tagline:             Build amazing page layouts using WordPress for free!
url:                 http://gettailor.com
paginate:            1
baseurl:             ""

# Server
destination:        _site
host:               0.0.0.0
port:               9000

sass:
  sass_dir:         assets/scss
  style:            :compressed

# About/contact
author:
  name:             Andrew Worsfold
  url:              http://www.andrewworsfold.com
  twitter:          https://twitter.com/andrewjworsfold
  facebook:         https://facebook.com/andrew.worsfold

tailor:
  wordpress:        https://wordpress.org/plugins/tailor/
  github:           https://wordpress.org/plugins/tailor/
  twitter:          https://twitter.com/tailorwp
  facebook:         https://facebook.com/tailorwp

# Dependencies
markdown:           kramdown
highlighter:        rouge

kramdown:
  auto_ids:         true

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

# Custom vars
repo:               https://github.com/andrewworsfold/tailor
twitter:            https://twitter.com/andrewjworsfold

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css
  css_hash:         "sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd"
  jquery:           https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
  jquery_hash:      "sha384-8gBf6Y4YYq7Jx97PIqmTwLPin4hxIzQw5aDmUg/DDhul9fFpbbLcLh3nTIIDJKhx"
